spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root

build:
  version: "1.0"

cards:
  message: "Hey, welcome to EasyBank cards related webhook APIs"
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
